version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build: 
      context: .
    ports:
      - "8080:8000"
  # redis:
  #   image: redis:alpine
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "81:80"
    depends_on:
      - django_gunicorn



  volumes:
    static:



volumes:
  static:
