# Generated by Django 4.2.1 on 2023-07-08 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('device_id', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('case_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('case', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('realtime_updates', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modes',
            fields=[
                ('mode_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('type_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('place_of_residence', models.CharField(max_length=100)),
                ('ghana_card_number', models.CharField(max_length=20)),
                ('ghana_card_picture', models.ImageField(default='images/default_ghana_card.jpg', upload_to='ghana_card_pictures/')),
                ('photo', models.ImageField(default='images/default_user.png', upload_to='user_photos/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staff_username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.cases')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('location_coordinate', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.user')),
            ],
        ),
        migrations.AddField(
            model_name='cases',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.staff'),
        ),
        migrations.AddField(
            model_name='cases',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.user'),
        ),
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('call_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('from_number', models.CharField(max_length=20)),
                ('duration', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.cases')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_server.staff')),
            ],
        ),
    ]
